import numpy as np
import ScatteringClass

Scatter1 = ScatteringClass.Scattering(1.6)
EnergyArray1 = Scatter1.Rutherford()
np.save("RutherfordData(1_6MeV).npy", EnergyArray1)
Scatter2 = ScatteringClass.Scattering(3.2)
EnergyArray2 = Scatter2.Rutherford()
np.save("RutherfordData(3_2MeV).npy", EnergyArray2)
Scatter3 = ScatteringClass.Scattering(4.8)
EnergyArray3 = Scatter3.Rutherford()
np.save("RutherfordData(4_8MeV).npy", EnergyArray3)
Scatter4 = ScatteringClass.Scattering(6.4)
EnergyArray4 = Scatter4.Rutherford()
np.save("RutherfordData(6_4MeV).npy", EnergyArray4)
Scatter5 = ScatteringClass.Scattering(8.0)
EnergyArray5 = Scatter5.Rutherford()
np.save("RutherfordData(8_0MeV).npy", EnergyArray5)
Scatter6 = ScatteringClass.Scattering(9.6)
EnergyArray6 = Scatter6.Rutherford()
np.save("RutherfordData(9_6MeV).npy", EnergyArray6)
Scatter7 = ScatteringClass.Scattering(11.2)
EnergyArray7 = Scatter7.Rutherford()
np.save("RutherfordData(11_2MeV).npy", EnergyArray7)
Scatter8 = ScatteringClass.Scattering(12.8)
EnergyArray8 = Scatter8.Rutherford()
np.save("RutherfordData(12_8MeV).npy", EnergyArray8)
Scatter9 = ScatteringClass.Scattering(14.4)
EnergyArray9 = Scatter9.Rutherford()
np.save("RutherfordData(14_4MeV).npy", EnergyArray9)
Scatter10 = ScatteringClass.Scattering(16.0)
EnergyArray10 = Scatter10.Rutherford()
np.save("RutherfordData(16_0MeV).npy", EnergyArray10)
Scatter11 = ScatteringClass.Scattering(17.6)
EnergyArray11 = Scatter11.Rutherford()
np.save("RutherfordData(17_6MeV).npy", EnergyArray11)
Scatter12 = ScatteringClass.Scattering(19.2)
EnergyArray12 = Scatter12.Rutherford()
np.save("RutherfordData(19_2MeV).npy", EnergyArray12)
Scatter13 = ScatteringClass.Scattering(20.8)
EnergyArray13 = Scatter13.Rutherford()
np.save("RutherfordData(20_8MeV).npy", EnergyArray13)
Scatter14 = ScatteringClass.Scattering(22.4)
EnergyArray14 = Scatter14.Rutherford()
np.save("RutherfordData(22_4MeV).npy", EnergyArray14)
Scatter15 = ScatteringClass.Scattering(24.0)
EnergyArray15 = Scatter15.Rutherford()
np.save("RutherfordData(24_0MeV).npy", EnergyArray15)
Scatter16 = ScatteringClass.Scattering(25.6)
EnergyArray16 = Scatter16.Rutherford()
np.save("RutherfordData(25_6MeV).npy", EnergyArray16)
Scatter17 = ScatteringClass.Scattering(27.2)
EnergyArray17 = Scatter17.Rutherford()
np.save("RutherfordData(27_2MeV).npy", EnergyArray17)
Scatter18 = ScatteringClass.Scattering(28.8)
EnergyArray18 = Scatter18.Rutherford()
np.save("RutherfordData(28_8MeV).npy", EnergyArray18)
Scatter19 = ScatteringClass.Scattering(30.4)
EnergyArray19 = Scatter19.Rutherford()
np.save("RutherfordData(30_4MeV).npy", EnergyArray19)
Scatter20 = ScatteringClass.Scattering(32.0)
EnergyArray20 = Scatter20.Rutherford()
np.save("RutherfordData(32_0MeV).npy", EnergyArray20)
Scatter21 = ScatteringClass.Scattering(33.6)
EnergyArray21 = Scatter21.Rutherford()
np.save("RutherfordData(33_6MeV).npy", EnergyArray21)
Scatter22 = ScatteringClass.Scattering(35.2)
EnergyArray22 = Scatter22.Rutherford()
np.save("RutherfordData(35_2MeV).npy", EnergyArray22)
Scatter23 = ScatteringClass.Scattering(36.8)
EnergyArray23 = Scatter23.Rutherford()
np.save("RutherfordData(36_8MeV).npy", EnergyArray23)
Scatter24 = ScatteringClass.Scattering(38.4)
EnergyArray24 = Scatter24.Rutherford()
np.save("RutherfordData(38_4MeV).npy", EnergyArray24)
Scatter25 = ScatteringClass.Scattering(40.0)
EnergyArray25 = Scatter25.Rutherford()
np.save("RutherfordData(40_0MeV).npy", EnergyArray25)
